resilience4j:
  circuitbreaker:
    configs:
      defecto:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
    instances:
      products:
        baseConfig: defecto
  timelimiter:
    configs:
      defecto:
        timeoutDuration: 6s
    instances:
      products:
        baseConfig: defecto
spring:
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**
#            - Header= token, \d+
#            - Method=GET, POST
#            - Query=color, green
#            - Cookie=color, blue
          filters:
            - name: CircuitBreaker
              args:
                name: products
                statusCodes: 500
                fallbackUri: forward:/api/items/items/9/amount/5
            - StripPrefix=2
            - SampleCookie= Hi mi custom message,User, MiguelCanessa
        - id: service-items
          uri: lb://service-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 654321
            - AddRequestParameter=name, Miguel