spring:
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
            - SampleCookie= Hi mi custom message,User, MiguelCanessa
        - id: service-items
          uri: lb://service-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 654321
            - AddRequestParameter=name, Miguel