spring:
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
            - name: Sample
              args:
                message: Hi, mi custom message
                cookieName: User
                cookieValue: MiguelCanessa
        - id: service-items
          uri: lb://service-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2